on:
  push:
    branches:
      - main

jobs:
  frontend:
    runs-on: sh-runner
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 20.12.2
      - name: Install dependencies
        working-directory: front
        run: npm ci
      - name: Lint
        working-directory: front
        run: npm run lint
      - name: Build
        working-directory: front
        run: npm run build
  api:
    runs-on: sh-runner
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup GoLang
        uses: actions/go@v5
        with:
          go-version: '^1.19'
      - name: Install dependencies
        run: go mod download
      - name: Build
        run: go build
